---
title: "IPCHEM Data Statistics"
output:
  flexdashboard::flex_dashboard:
    # logo: ./logo/eu.jpg
    vertical_layout: scroll
    orientation: rows
    css: custom.css
---

```{r setup, include=FALSE}
library(stringr)
library(tidyverse)
library(DT)
library(plotly)
library(flexdashboard)
library(leaflet)
library(lubridate)
source("fnutils.R")
```

Sidebar {.sidebar}
=======================================================================

This space is reserved for adding information about the charts and tables in the dashboard.

<hr>

<!-- <style> -->
<!--         strong { -->
<!--             font-weight: bold; -->
<!--         } -->
<!--         navbar { -->
<!--             display: none; -->
<!--         } -->
<!-- </style> -->

<p>This report was created on:</p>

<!-- <strong id="currentDate"></strong> -->
<!-- <script> -->
<!--   var currentDate = new Date(); -->
<!--   var day = currentDate.getDate(); -->
<!--   var month = currentDate.toLocaleString('default', { month: 'short' }); // Using the toLocaleString method to get the short month name -->
<!--   var year = currentDate.getFullYear(); -->

<!--   var formattedDate = day + '-' + month.toUpperCase() + '-' + year; -->

<!--   document.getElementById('currentDate').innerHTML = formattedDate; -->
<!-- </script> -->

<strong>
`r Sys.Date()`
</strong>



```{r import_data, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

# load main data

url = "https://ipchem.jrc.ec.europa.eu/public/IPCHEM_public_dataset_packages.csv"

list_of_packages = get_csv_url(url)
list_of_packages = chg_col_names(list_of_packages)

world_cities <-
  read.table(
    "./data/worldcities.csv",
    header = TRUE,
    sep = ",",
    quote = "\"",
    dec = ".",
    encoding = "UTF-8"
  )

coordinates <- world_cities %>% 
  dplyr::filter(capital == 'primary')
```


```{r global, echo=FALSE, warning=FALSE}

list_of_packages = list_of_packages %>% 
  dplyr::filter(!is.na(chemical_name)) %>% 
  dplyr::filter(!is.na(period)) %>% 
  dplyr::filter(!str_like(location, "%null%"))

# counts
n_datasets = length(unique(list_of_packages$dataset[list_of_packages$dataset != ""]))
n_packages = length(unique(list_of_packages$package[list_of_packages$media != ""]))

# sums

sum_records = sum(list_of_packages$records[list_of_packages$media != ""])

# create pivot tables
pivot_media <- list_of_packages %>%
  group_by(media) %>%
  summarize(
    packages = n(),
    records = sum(records)
    ) %>% 
  ungroup() %>% 
  arrange(desc(records))

pivot_media_period <- list_of_packages %>%
  group_by(media, period) %>%
  summarize(records = sum(records))

# record and packages by dataset
pivot_dataset = list_of_packages %>% 
  group_by(dataset) %>% 
  summarize(
    packages = n(),
    records = sum(records)
    )%>% 
  ungroup() %>% 
  arrange(desc(records))

pivot_dataset_period = list_of_packages %>%
  group_by(dataset, period) %>%
  summarize(records = sum(records))

# record by module and period
pivot_module = list_of_packages %>% 
  select(dataset, records) %>% 
  left_join(env_modules, by = join_by(dataset == dataset)) %>% 
  group_by(module) %>% 
  summarize(records = sum(records))%>% 
  ungroup() %>% 
  arrange(desc(records))

# record by module and period
pivot_module_period = list_of_packages %>% 
  select(dataset, period, records) %>% 
  left_join(env_modules, by = join_by(dataset == dataset)) %>% 
  group_by(module, period) %>% 
  summarize(records = sum(records))

# number of record by year
pivot_period <- list_of_packages %>%
  group_by(period) %>%
  summarize(records = sum(records))

# split column location by each individual country and extract records
locations <- list_of_packages %>% 
  select(location, period, chemical_name) %>% 
  separate_rows(location, sep = ", ", convert = TRUE) %>% 
  mutate(country_code = str_split_fixed(location, ' \\[', 2)[, 1]) %>% 
  mutate(score = str_split_fixed(location, ' \\[', 2)[, 2]) %>%
  mutate(score = as.numeric(str_sub(score, 1, str_length(score) - 1))) %>% 
  select(-location)

# number or record by country
pivot_country = locations %>% 
  dplyr::filter(!is_null(country_code)) %>%
  dplyr::filter(country_code != "null") %>%
  group_by(country_code) %>% 
  summarize(scores = sum(score))

# number of records by country an period
pivot_country_period = locations %>%
  # dplyr::filter(!is_null(country_code)) %>% 
  # dplyr::filter(country_code != "null") %>%
  # dplyr::filter(country_code != "N/A") %>%
  # # dplyr::filter(!is.na(period)) %>% 
  group_by(country_code, period) %>%
  summarize(scores = sum(score)) %>% 
  ungroup()

# bring the nice name of the country
pivot_country_period = pivot_country_period %>% 
  left_join(coordinates %>% 
              select(country, iso3) %>% 
              distinct(), # some countries have more than 1 primary city
            by = join_by(country_code == iso3)) %>% 
  filter(!is.na(country)) %>% # 1A0 country code does not exist in coordinates. what is it?
  select(country, period, scores)

# which chemical has most of the records. top 10
chemical_pivot = list_of_packages %>% 
  filter(!is.na(chemical_name)) %>% 
  group_by(chemical_name) %>% 
  summarize(n = sum(records)) %>% 
  arrange(desc(n)) %>% 
  head(20)

# after split by country, sum the chemical records by country only for top chemicals
pivot_chemical_country = locations %>%
  inner_join(chemical_pivot %>% select(chemical_name),
             by = join_by(chemical_name == chemical_name)) %>%
  group_by(chemical_name, country_code) %>%
  summarize(records = sum(score))

# bring the nice name of the country
pivot_chemical_country = pivot_chemical_country %>% 
  left_join(coordinates %>% 
              select(country, iso3) %>% 
              distinct(), # some countries have more than 1 primary city
            by = join_by(country_code == iso3)) %>% 
  filter(!is.na(country)) %>% # 1A0 country code does not exist in coordinates. what is it?
  select(chemical_name, country, records)


# # create also the total for each country are record it as a country
# pivot_country_period = pivot_country_period %>% 
#   bind_rows(pivot_country_period %>% 
#               group_by(period) %>% 
#               summarize(scores = sum(scores)) %>% 
#               mutate(country = "TOTAL") %>% 
#               select(country, period, scores))

# create map
# extract coordinates for each country capital 
country_coordinates <- pivot_country %>%
  left_join(coordinates, by = join_by(country_code == iso3)) %>%
  filter(!is.na(city))

# label for pin on map
content_popup <- paste(
  sep = "<br/>",
  paste("<b>", country_coordinates$country, "</b>"),
  format(country_coordinates$scores, big.mark = ",")
)

content_label <-
  paste(
    country_coordinates$country,
    ": ",
    format(country_coordinates$scores, big.mark = ",")
  )


```

```{r}
# cleanup

rm(list_of_packages, locations, world_cities)

```

Dashboard
=======================================================================

Row
-------------------------------------

### Number of Datasets

```{r}

valueBox(prettyNum(n_datasets, big.mark = ","), icon = "fa-database", color = "blue")

```

### Number of Packages

```{r}

valueBox(prettyNum(n_packages, big.mark = ","), icon = "fa-database", color = "orange")

```

### Number of Records

```{r}

valueBox(prettyNum(sum_records, big.mark = ","), icon = "fa-database", color = "green")

```


Row
-------------------------------------
### Records per year

```{r}

fig <-
  plot_ly(
    x = ~ country,
    y = ~ records,
    data = pivot_chemical_country,
    type = 'bar',
    name = ~chemical_name
  ) %>%
  layout(
    # title = 'Records per year',
    plot_bgcolor = '#e5ecf6',
    xaxis = list(
      title = 'Country',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    yaxis = list(
      title = 'Number of Records',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    )
  )

fig


# fig <-
#   plot_ly(
#     x = ~ period,
#     y = ~ records,
#     data = pivot_period,
#     type = 'bar'
#   ) %>%
#   layout(
#     # title = 'Records per year',
#     plot_bgcolor = '#e5ecf6',
#     xaxis = list(
#       title = 'Year',
#       zerolinecolor = '#ffff',
#       zerolinewidth = 2,
#       gridcolor = 'ffff'
#     ),
#     yaxis = list(
#       title = 'Number of Records',
#       zerolinecolor = '#ffff',
#       zerolinewidth = 2,
#       gridcolor = 'ffff'
#     )
#   )
# 
# fig
```



Row
-------------------------------------

### Module

```{r}

fig <-
  pivot_module_period %>%
  filter(period >= 1990) %>%
  # mutate(module = str_sub(module, 1, 10)) %>% # so the legend won't be pushed right
  plot_ly(
    x = ~ period,
    y = ~ records,
    # data = pivot_country_period,
    type = 'scatter',
    mode = "lines",
    name = ~ module,
    fill = 'tozeroy'
  ) %>%
  layout(
    # title = 'Records per year and country',
    plot_bgcolor = '#e5ecf6',
    xaxis = list(
      title = 'Year',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    yaxis = list(
      title = 'Number of Records',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    legend = list(x = 0.1, y = 0.9),
    showlegend = TRUE
  )

fig

```



### Media
```{r}

fig <-
  pivot_media_period %>%
  filter(period >= 1990) %>%
  # mutate(media = str_sub(media, 1, 10)) %>% # so the legend won't be pushed right
  plot_ly(
    x = ~ period,
    y = ~ records,
    # data = pivot_country_period,
    type = 'scatter',
    mode = "lines",
    name = ~ media,
    fill = 'tozeroy'
  ) %>%
  layout(
    # title = 'Records per year and dataset',
    plot_bgcolor = '#e5ecf6',
    xaxis = list(
      title = 'Year',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    yaxis = list(
      title = 'Number of Records',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    legend = list(x = 0.1, y = 0.9),
    showlegend = TRUE
  )

fig

```

### Dataset
```{r}

fig <-
  pivot_dataset_period %>%
  filter(period >= 1990) %>%
  # mutate(dataset = str_sub(dataset, 1, 10)) %>% # so the legend won't be pushed right
  plot_ly(
    x = ~ period,
    y = ~ records,
    # data = pivot_country_period,
    type = 'scatter',
    mode = "lines",
    name = ~ dataset,
    fill = 'tozeroy'
  ) %>%
  layout(
    # title = 'Records per year and dataset',
    plot_bgcolor = '#e5ecf6',
    xaxis = list(
      title = 'Year',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    yaxis = list(
      title = 'Number of Records',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    legend = list(x = 0.1, y = 0.9),
    showlegend = TRUE
  )

fig
```

Row
-------------------------------------

### Statistics by Module

```{r}

DT::datatable(pivot_module,
              options = list(dom = 't',
                             bPaginate = FALSE))

```

### Statistics by Media

```{r}
DT::datatable(pivot_media,
              options = list(dom = 't',
                             bPaginate = FALSE)) 

```

### Statistics by Dataset

```{r}


DT::datatable(pivot_dataset,
              options = list(dom = 't',
                             bPaginate = FALSE))

```




Row
-------------------------------------

### Map distribution of data records

```{r}


m <-
  leaflet(data = country_coordinates, options = leafletOptions(minZoom = 2, maxZoom = 9)) %>%
  setView(14.4214, 50.0875, zoom = 3) %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  #addProviderTiles("OpenStreetMap.Mapnik") %>%
  
  addMarkers(
    ~ lng,
    ~ lat,
    popup = ~ as.character(content_popup),
    label = ~ as.character(content_label)
  )

m  # Print the map

```


### Country level records by year

```{r}

fig <-
  pivot_country_period %>%
  filter(period >= 1990) %>% 
  mutate(country = str_sub(country, 1, 13)) %>% # so the legend won't be pushed right
  plot_ly(
    x = ~ period,
    y = ~ scores,
    # data = pivot_country_period,
    type = 'scatter',
    mode = "lines",
    name = ~ country
  ) %>%
  layout(
    # title = 'Records per year and country',
    plot_bgcolor = '#e5ecf6',
    xaxis = list(
      title = 'Year',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    yaxis = list(
      title = 'Number of Records',
      zerolinecolor = '#ffff',
      zerolinewidth = 2,
      gridcolor = 'ffff'
    ),
    showlegend = TRUE
  )

fig

```

